services:
  app:
    image: safiakhoulaid/smartlogi-backend:latest
    container_name: spring-app
    pull_policy: always
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Use Standard Spring Variables
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/smartlogi_db_v2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"

      # Hibernate & Liquibase coordination
      SPRING_LIQUIBASE_ENABLED: "true"
      # IMPORTANT: Diri 'none' hna bach tkhalli Liquibase howa l-m3llem
      # hit 'validate' ghat-planti lik ila kan l-farq f 'depot_attitide'
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: smartlogi_db_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartlogi_db_v2"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always

volumes:
  postgres_data_prod: