services:
  app:
    image: safiakhoulaid/smartlogi-backend:latest
    container_name: spring-app
    pull_policy: always
    restart: always
    ports:
      - "8080:8080"
      # - "5005:5005"  <-- 7iyedto 3la wed sécurité
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://db:5432/smartlogi_db_v2
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 1234
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: smartlogi_db_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432" # Khalih ghir ila konti bagha accès mn barra
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

volumes:
  postgres_data_prod: