spring:
  application:
    name: sdms-api

  # Liquibase
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: safiakhoulaid11@gmail.com
    password: ${MAIL_PASSWORD:rzmbeusgvddkdoix}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  # Config JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Security OAuth2
  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 61172088660-h3c3gutkcb3nj04n2l6o07afqs77p9a2.apps.googleusercontent.com
#            client-secret: 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
#            scope: openid, profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
    oauth2:
      client:
        registration:
          okta:
            client-id: X9Yzl0yQuLeYsW1mFtrnXLP5IGYbw9AU
            client-secret: Txtu16by0cofZuF1K0ztonNeVBri-CyGPyW-rpZfcqjyXhEacXj7lQ5__HvrihqG
            scope: openid, profile, email
        provider:
          okta:
            issuer-uri: https://dev-tsljattis1gpus20.us.auth0.com/



  ai:
    openai:
      api-key: sk-26584b79877f4cf3a6405306140ebcdf
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.0

# Configuration Swagger (Bo7dha)
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    defaultModelsExpandDepth: 1
    displayRequestDuration: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:e41cd8d26ff1ee82eb8d271b14f247f7c24ff9189aca42f6f3c841f4bb7c60da}
      expiration: 86400000