spring:
  #connection aau base de donn�e
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  #configuration de jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  #configuration Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

#configuration de server
server:
  port: 8080
  servlet:
    context-path: /api
