spring:
  application:
    name: sdms-api

  # Liquibase
  liquibase:
    change-log: db/changelog/db.changelog-master.xml

  # Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: safiakhoulaid11@gmail.com
    password: ${MAIL_PASSWORD:rzmbeusgvddkdoix}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  # Config JPA
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ðŸ‘‡ HNA FIN KHASSHA TKOUN (Malignya m3a jpa, mail, etc.)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 61172088660-h3c3gutkcb3nj04n2l6o07afqs77p9a2.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

# Configuration Swagger (Bo7dha)
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    defaultModelsExpandDepth: 1
    displayRequestDuration: true