name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout l-Code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      # 3. Build l-Projet (skip tests)
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 4. Login l-Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Build & Push Image l-Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: safiakhoulaid/smartlogi-backend:latest

      # 6. Deployment f EC2 (AWS)
      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # صيفطي docker-compose لـ serveur
          scp -o StrictHostKeyChecking=no -i private_key.pem docker-compose.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/home/${{ secrets.EC2_USER }}/

          # تخدمي docker-compose فـ serveur
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
            cd /home/${{ secrets.EC2_USER }}/
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
          EOF

      # (ReAct Mode)
      - name: Run Tests & Capture Log

        run: mvn clean verify > build.log 2>&1 || true

      - name: AI Analysis (ReAct Mode)
        if: always()
        run: |
          curl -X POST http://51.21.186.55:8080/api/v1/ai/analyze-cicd \
               -H "Content-Type: text/plain" \
               --data-binary "@build.log"