name: Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # A - Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # B - Install Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # C - Make mvnw executable
      - name: Make mvnw executable
        run: chmod +x mvnw

      # D - Build
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # E - Run tests
      - name: Run Unit Tests
        run: ./mvnw test

      # F - Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # G - Build & Push image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/smartlogi-backend:latest
